CREATE TABLE riac.Usuarios
	(Id_Usuario INT AUTO_INCREMENT NOT NULL, 
	Nombre VARCHAR(255) NOT NULL, 
	ApellidoP VARCHAR(255) NOT NULL, 
	ApellidoM VARCHAR(255) NOT NULL, 
	Telefono VARCHAR(255) NOT NULL, 
	Email VARCHAR(255) NOT NULL,  
	Password VARCHAR(255) NOT NULL,
	UserName VARCHAR (255)  NOT NULL,
	Online INT NOT NULL,
	Img_Usuario VARCHAR(255) NULL,
	Id_Plantel INT NOT NULL, 
	Id_TUsuario INT NOT NULL, 
	Id_Estatus INT NOT NULL,
	Id_Expediente INT NOT NULL,
	FOREIGN KEY (Id_Plantel) REFERENCES Planteles (Id_Plantel),
	FOREIGN KEY (Id_TUsuario) REFERENCES TUsuarios (Id_TUsuario),
	FOREIGN KEY (Id_Estatus) REFERENCES Estatus (Id_Estatus),
	FOREIGN KEY (Id_Expediente) REFERENCES Expedientes (Id_Expediente),
	PRIMARY KEY(Id_Usuario)) ENGINE = InnoDB;
