CREATE TABLE riac.Informes
	(Id_Informe INT AUTO_INCREMENT NOT NULL, 
	 Id_Modulo INT NOT NULL,
         N_Tutor VARCHAR (255) NOT NULL,
         Id_Grupo INT NOT NULL,
         Id_Carrera INT NOT NULL, 
         Id_Turno INT NOT NULL,
         Id_Mes INT NOT NULL, 
         Fecha_Entrega DATE NOT NULL, 
         Id_Usuario INT NOT NULL, 
         Id_Genero INT NOT NULL,
         Id_Problematica INT NOT NULL,
         Observacion VARCHAR (500) NULL,
         Id_Accion_Realizada INT NOT NULL,
         Sugerencia TEXT NULL,
         FOREIGN KEY (Id_Modulo) REFERENCES Modulos (Id_Modulo),
	 FOREIGN KEY (Id_Grupo) REFERENCES Grupos (Id_Grupo),
         FOREIGN KEY (Id_Carrera) REFERENCES Carreras (Id_Carrera),
         FOREIGN KEY (Id_Turno) REFERENCES Turno (Id_Turno),
         FOREIGN KEY (Id_Mes) REFERENCES Meses (Id_Mes),
         FOREIGN KEY (Id_Usuario) REFERENCES Usuarios (Id_Usuario),
         FOREIGN KEY (Id_Genero) REFERENCES Genero (Id_Genero),
         FOREIGN KEY (Id_Accion_Realizada) REFERENCES Accion_Realizada (Id_Accion_Realizada),
         PRIMARY KEY (Id_Informe)) ENGINE = InnoDB;